services:
  builder:
    build: .
    image: ergo-s1-zmk-builder:latest
    container_name: ergo-s1-zmk-builder
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      PORT: 8080
      APP_BASE_URL: http://localhost:8080
    restart: unless-stopped
