services:
  builder:
    build: .
    image: ergo-s1-zmk-builder:latest
    container_name: ergo-s1-zmk-builder
    ports:
      - "8090:8090"
    env_file:
      - .env
    environment:
      PORT: 8090
      APP_BASE_URL: http://localhost:8090
    restart: unless-stopped
